<div class="gem-c-breadcrumbs govuk-breadcrumbs " data-module="track-click">
    <ol class="govuk-breadcrumbs__list">
        <li class="govuk-breadcrumbs__list-item" aria-current="false">
            <a data-track-category="homeLinkClicked" data-track-action="homeBreadcrumb" data-track-label="" data-track-options="{}" class="govuk-breadcrumbs__link" aria-current="false" href="javascript:history.go(-1)">Back to previous page</a>
        </li>
    </ol>
</div>

<div class="gem-c-title govuk-!-margin-top-8 govuk-!-margin-bottom-8">
    <h1 class="gem-c-title__text ">
        Cookies
    </h1>
</div>

<div class="gem-c-govspeak govuk-govspeak " data-module="govspeak">
    <p>Cookies are files saved on your phone, tablet or computer when you visit a website.</p>
    <p>We use cookies to store information about how you use the Vehicle Operator Licensing website, such as the pages you visit.</p>
</div>

<div class="cookie-settings__form-wrapper">
    <h2 class="gem-c-heading gem-c-heading--padding govuk-!-margin-top-7">Cookie settings</h2>
    <p>We use 4 types of cookie. You can choose which cookies you're happy for us to use.</p>
    <form data-module="cookie-settings">
        <div class="govuk-form-group">
            <fieldset class="govuk-fieldset" aria-describedby="hint-aed44408">
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
                    <h3 class="govuk-heading-m govuk-!-margin-top-7">Cookies that measure website use</h3>
                </legend>

                <div id="hint-aed44408" class="gem-c-hint govuk-hint govuk-!-margin-bottom-3">
                    We use Google Analytics to measure how you use the website so we can improve it based on user needs. We do not allow Google to use or share the data about how you use this site.<br><br>

                    Google Analytics sets cookies that store anonymised information about:
                    <ul>
                        <li>how you got to the site</li>
                        <li>the pages you visit when using this service, and how long you spend on each page</li>
                        <li>what you click on while you're visiting the site</li>
                    </ul>

                </div>
                <div class="govuk-radios govuk-radios--inline">
                    <div class="gem-c-radio govuk-radios__item">
                        <input type="radio" name="cookies-usage" id="radio-fc9e63d9-0" value="on" class="govuk-radios__input">

                        <label for="radio-fc9e63d9-0" class="gem-c-label govuk-label govuk-radios__label">
                            <span class="translation_missing" title="translation missing: en.cookies.on">On</span>
                        </label>
                    </div>
                    <div class="gem-c-radio govuk-radios__item">
                        <input type="radio" name="cookies-usage" id="radio-fc9e63d9-1" value="off" class="govuk-radios__input">

                        <label for="radio-fc9e63d9-1" class="gem-c-label govuk-label govuk-radios__label">
                            <span class="translation_missing" title="translation missing: en.cookies.off">Off</span>
                        </label>
                    </div>
                </div>
            </fieldset>
        </div>

        <!-- Cookies that remember your settings -->
        <div class="govuk-form-group">
            <fieldset class="govuk-fieldset" aria-describedby="hint-2a73cd62">
                <legend class="govuk-fieldset__legend govuk-fieldset__legend--m">
                    <h3 class="govuk-heading-m">Cookies that remember your settings</h3>
                </legend>

                <div id="hint-2a73cd62" class="gem-c-hint govuk-hint govuk-!-margin-bottom-3">
                    These cookies do things like remember your preferences and the choices you make, to personalise your experience of using the site.
                </div>
                <div class="govuk-radios govuk-radios--inline">
                    <div class="gem-c-radio govuk-radios__item">
                        <input type="radio" name="cookies-settings" id="radio-110c727c-0" value="on" class="govuk-radios__input">

                        <label for="radio-110c727c-0" class="gem-c-label govuk-label govuk-radios__label">
                            <span class="translation_missing" title="translation missing: en.cookies.on">On</span>
                        </label>
                    </div>
                    <div class="gem-c-radio govuk-radios__item">
                        <input type="radio" name="cookies-settings" id="radio-110c727c-1" value="off" class="govuk-radios__input">

                        <label for="radio-110c727c-1" class="gem-c-label govuk-label govuk-radios__label">
                            <span class="translation_missing" title="translation missing: en.cookies.off">Off</span>
                        </label>
                    </div>
                </div>
            </fieldset>
        </div>

        <!-- Site security cookies -->
        <div class="gem-c-govspeak govuk-govspeak govuk-!-margin-top-7" data-module="govspeak">
            <h3 class="govuk-heading-m" style="font-size: 24px !important">Security cookies</h3>
            <p>These essential cookies are part of the service security defences and keep your information safe as you move through the service.</p>
            <p>They always need to be on.</p>
        </div>

        <!-- Strictly necessary cookies -->
        <div class="gem-c-govspeak govuk-govspeak govuk-!-margin-top-7" data-module="govspeak">
            <h3 class="govuk-heading-m" style="font-size: 24px !important">Strictly necessary cookies</h3>
            <p>These cookies are essential in order to enable you to start using the service, move around the website and use its features. Without these cookies the services you would like to use cannot be provided.</p>
            <p>They always need to be on.</p>
            <p>
                <a href="/consent/cookies/cookies-details" data-module="track-click" data-track-category="cookieSettings" data-track-action="Find out more about cookies">
                    Find out more about cookies on Vehicle Operator Licensing service
                </a>
            </p>
        </div>

        <button class="gem-c-button govuk-button" type="submit">Save changes</button>
    </form>
</div>

<div class="cookie-settings__gov-services">
    <h3 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Third-party cookies</h3>
    <p>Vehicle Operator Licensing integrates and redirects users to some third-party service suppliers. These services may also set cookies on your device when you visit their pages.</p>
</div>

<div class="cookie-settings__gov-services">
    <h3 class="govuk-heading-m govuk-!-margin-top-7" style="font-size: 24px !important">Government services</h3>
    <p>Most services we link to are run by different government departments, for example, DVLA’s vehicle tax service or GOV.UK Verify. These services may set additional cookies and, if so, will have their own cookie policy and banner linking to it.</p>
</div>
